# Generated by Django 3.2.15 on 2022-10-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comment_post',
        ),
    ]
