# Generated by Django 3.2.15 on 2022-10-10 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_rename_comment_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_upload'),
        ),
        migrations.AlterField(
            model_name='comment_post',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='main.blogpost'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to=settings.AUTH_USER_MODEL),
        ),
    ]
